### PR TITLE
Replace parameter "ts" by "iat" for jws and jwsd key proofing mechanisms.

### PR DESCRIPTION
**Pull request by adeinega**
Suggested changes for https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/202#issuecomment-808941552

### CODE REVIEW

**Comment by fimbault** [comment]
Yes, although that lacks information on the reference used. 

Either we could refer to https://tools.ietf.org/html/rfc7519#section-2 (NumericDate) or explain that iat's canonicalized value is an Integer String containing the signature's Creation Time expressed as the number of seconds since the Epoch, as defined in Section 4.16 of [POSIX.1].

**Comment by yaronf** [comment]
> Yes, although that lacks information on the format (integer seconds) and reference used.
> 
> Either we could refer to https://tools.ietf.org/html/rfc7519#section-2 (NumericDate) or explain that iat's canonicalized value is an Integer String containing the signature's Creation Time expressed as the number of seconds since the Epoch, as defined in Section 4.16 of [POSIX.1].

IMO the reference to 7519 is most appropriate.

**Comment by adeinega** [comment]
Done. I really like `NumericDate` but didn't want to add it initially as that would add an additional dependency to RFC 7519. There is absolutely nothing wrong with it except one thing, this RFC talks about JWTs, not JWS objects and it uses `NumericDate` for claims such as `iat` and `nbf`, nor header parameters.

**Comment by adeinega** [comment]
Note, I used `number` as the JSON data type.

**Comment by jricher** [comment]
Note that these are JWS header values, not JWT payload claims. I would also prefer not to pull JWT into this, since the proofs are not the same as tokens and they shouldn't be able to be confused as one. Not saying I'm against this change of syntax, but we'd be defining (and registering) a new header field anyway. 

As such, I have a slight preference to keep `ts` since this proof isn't "issued" like a token is, so much as just "created".

**Comment by fimbault** [comment]
I agree keeping jwt out of this is best, hence the suggestion to simply describe what is expected (and we currently have a description that it is expressed in seconds, which goes in that direction).

**Comment by fimbault** [comment]
We should consider renaming the field, but it should be distinct from iat because it's not a JWT.

**Comment by adeinega** [comment]
For me, it isn't a big issue with reusing `iat` as is even if it overlaps with JWTs. We just need to remove a reference to RFC 7519 and provide our own description. The reason is that in programming languages, we offen use the same variable names like `i` below

```
String[] fruits = {"apple", "banana", pear"};
for (String i : fruits) {
    eat(i)
}

String[] veggies = {"broccoli", "carrot", "cucumber"};
for (String i : veggies) {
    eat(i)
}
```

and have zero issues with that, right?

If you want to use something distinct, I would suggest `rat` (requested at)... and yes, naming is hard.

**Comment by jricher** [comment]
I would personally be more comfortable with `created` or the like, as that's what's being indicated here. It's a signature object, not a token -- it was not "requested" and it was not "issued" like a token would be.

**Comment by fimbault** [comment]
so we need to choose between `rat` and `cat` ;-)

**Comment by fimbault** [comment]
Closing. (Editors hat off) I suggest creating a new PR for created at, to replace ts.

**Comment by fimbault** [comment]
Closing. (Editors hat off) I suggest creating a new PR for created at, to replace ts.

**Pull request closed without merging**
