### PR TITLE
These are examples of not sender-constrained tokens. Hence, the "bound" v…

### PR DESCRIPTION
**Pull request by adeinega**
…alue should be the boolean false.

Please, correct me if I wrong.

### CODE REVIEW

**Review by jricher — CHANGES_REQUESTED** [review]
The intent was to make the examples bound tokens by default, so instead of changing the examples, any text surrounding these examples referring them as bearer needs to be adjusted appropriately.

**Comment by adeinega** [comment]
Ok, I will take care of it a bit later. I also suggest omitting `"bound": true` from other examples as it's a default value.

**Comment by adeinega** [comment]
Done.

**Comment by jricher** [comment]
We'll need to add an example of `bound: "true"` in at least one location, but otherwise these changes are good.

**Comment by adeinega** [comment]
Done in https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/209/commits/23bd329e9c764cedfe6a8dd1e26b557aa8fda9a6.

**Pull request merged**
