### PR TITLE
Consistent use of "end-user" instead of "end user"

### PR DESCRIPTION
**Pull request by pq2**
Section 1.2 only defines the role of an `end-user`, so I thought this should be written consistently that way.

### CODE REVIEW

**Review by jricher — APPROVED** [review]
I think this is the correct move, but I'd like to hear what @aaronpk and @fimbault think about the changes.

**Comment by fimbault** [comment]
Yes that's good

**Comment by fimbault** [comment]
Upon review (thanks Aaron), it should be unhyphenated as a noun. We sure need to be consistent everywhere.
See https://en.wikipedia.org/wiki/End_user

**Comment by pq2** [comment]
I have replaced the unambiguous uses of "end-user" as a noun with "end user". I am not sure about "end-user roles" in line 232 and "Exposure of end-user credentials" in line 4878. I left these lines as before (hyphenated). Someone else should look at these lines again.

**Pull request merged**
